"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { DashboardData, PeriodKey } from "@/types/activity";
import { DailyChart, type TrendMetric } from "./daily-chart";

const periods:{key:PeriodKey;label:string}[]=[{key:"today",label:"Today"},{key:"week",label:"7 Days"},{key:"month",label:"30 Days"}];
const fmt=new Intl.NumberFormat("en-US"); const compact=new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1});
const dateFmt=(v:string|null)=>v?new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—";
type SortKey="commits"|"changedLines"|"changedFiles"|"activeDays"|"score"|"momentum"|"pushedAt";
const metricLabels:Record<TrendMetric,string>={commits:"Commits",changedLines:"Lines",changedFiles:"Files",score:"Score"};

function Panel({title,sub,children}:{title:string;sub?:string;children:React.ReactNode}){return <article className="panel min-w-0 p-3"><div className="mb-2 flex items-center justify-between"><h2 className="text-[11px] font-bold uppercase tracking-[.12em] text-[#7ee787]">{title}</h2>{sub&&<span className="muted text-[9px]">{sub}</span>}</div>{children}</article>}
function Bars({items}:{items:{label:string;value:number;text:string;color?:string}[]}){const max=Math.max(1,...items.map(i=>i.value));return <div className="space-y-2">{items.map(i=><div key={i.label}><div className="mb-1 flex justify-between text-[10px]"><span className="truncate">{i.label}</span><span className="muted tabular-nums">{i.text}</span></div><div className="h-1.5 rounded bg-[#21262d]"><div className="h-full rounded" style={{width:`${i.value/max*100}%`,background:i.color??"#3fb950"}}/></div></div>)}</div>}

export function Dashboard({data}:{data:DashboardData}){
  const [period,setPeriod]=useState<PeriodKey>("week"); const [trendMetric,setTrendMetric]=useState<TrendMetric>("commits"); const [trendDays,setTrendDays]=useState<30|90>(30); const [sort,setSort]=useState<SortKey>("score");
  const summary=data.analysis.summaries[period],focus=data.analysis.focus[period],momentum=data.analysis.momentum;
  const rows=useMemo(()=>[...data.repositories].sort((a,b)=>{if(sort==="momentum")return momentum[b.repository.fullName].value-momentum[a.repository.fullName].value;if(sort==="pushedAt")return String(b.repository.pushedAt).localeCompare(String(a.repository.pushedAt));return b.metrics[period][sort]-a.metrics[period][sort]}),[data.repositories,momentum,period,sort]);
  const shares=useMemo(()=>{const active=[...data.repositories].filter(r=>r.metrics[period].score>0).sort((a,b)=>b.metrics[period].score-a.metrics[period].score);const total=active.reduce((s,r)=>s+r.metrics[period].score,0);const top=active.slice(0,5).map(r=>({label:r.repository.name,value:r.metrics[period].score,text:`${total?Math.round(r.metrics[period].score/total*100):0}%`}));const other=active.slice(5).reduce((s,r)=>s+r.metrics[period].score,0);return other>0?[...top,{label:"Other",value:other,text:`${Math.round(other/total*100)}%`}]:top},[data.repositories,period]);
  const kpis:[string,string][]=[["Commits",fmt.format(summary.commits)],["Changed Lines",compact.format(summary.changedLines)],["Additions",`+${compact.format(summary.additions)}`],["Deletions",`-${compact.format(summary.deletions)}`],["Files Changed",fmt.format(summary.changedFiles)],["Active Repos",String(focus.activeRepositories)],["Active Days",String(data.analysis.activeDays[period])],["Commits / Day",data.analysis.activeDays[period]?(summary.commits/data.analysis.activeDays[period]).toFixed(1):"0"],["Lines / Commit",summary.commits?compact.format(summary.changedLines/summary.commits):"0"],["Top Repo Share",`${focus.topShare}%`],["Current Streak",`${data.analysis.streak}d`],["API Remaining",data.rateLimit?compact.format(data.rateLimit.remaining):"—"]];
  const heat=data.dailyActivity; const maxHeat=Math.max(1,...heat.map(d=>d.score)); const slots=["00–06","06–12","12–18","18–24"],days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]; const maxHour=Math.max(1,...data.analysis.dayHour[period].map(c=>c.commits));
  return <main className="shell cockpit"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--line)] pb-3"><div><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[var(--green)] shadow-[0_0_12px_#3fb950]"/><span className="eyebrow">GitHub Monitor / Live</span></div><h1 className="mt-1 text-xl font-semibold">Developer Cockpit</h1></div><div className="flex rounded-md border border-[var(--line)] bg-[#0d1117] p-0.5">{periods.map(p=><button key={p.key} onClick={()=>setPeriod(p.key)} aria-pressed={period===p.key} className={`rounded px-3 py-1.5 text-[10px] font-bold ${period===p.key?"bg-[#238636]":"muted"}`}>{p.label}</button>)}</div></header>
  {data.warnings.length>0&&<div className="mt-2 rounded border border-amber-800/60 bg-amber-950/20 px-3 py-1.5 text-[10px] text-amber-200">Partial data · {data.warnings.length} repository request failed</div>}
  <section className="mt-2 grid grid-cols-2 gap-1.5 sm:grid-cols-3 lg:grid-cols-6">{kpis.map(([label,value])=><div key={label} className="panel px-3 py-2"><p className="muted text-[9px] uppercase">{label}</p><p className="mt-1 text-lg font-semibold tabular-nums">{value}</p></div>)}</section>
  <section className="mt-2 grid gap-2 xl:grid-cols-[1.35fr_.65fr]"><Panel title="Activity Trend" sub={`${trendDays} days`}><div className="mb-1 flex flex-wrap gap-1">{(["commits","changedLines","changedFiles","score"] as TrendMetric[]).map(m=><button key={m} onClick={()=>setTrendMetric(m)} className={`rounded px-2 py-1 text-[9px] ${trendMetric===m?"bg-[#238636]":"bg-[#21262d] muted"}`}>{metricLabels[m]}</button>)}<span className="ml-auto flex gap-1">{([30,90] as const).map(d=><button key={d} onClick={()=>setTrendDays(d)} className={`rounded px-2 py-1 text-[9px] ${trendDays===d?"bg-white/15":"muted"}`}>{d}D</button>)}</span></div><DailyChart data={data.dailyActivity.slice(-trendDays)} metric={trendMetric}/></Panel><Panel title="Repository Share" sub="Activity Score"><div className="mb-3 flex h-4 overflow-hidden rounded">{shares.map((s,i)=><div key={s.label} title={`${s.label} ${s.text}`} style={{width:s.text,background:["#56d364","#2ea043","#238636","#196c2e","#144620"][i]}}/>)}</div><Bars items={shares}/><div className="mt-3 grid grid-cols-3 border-t border-[var(--line)] pt-2 text-center text-[10px]"><span><b>{focus.score}</b><br/><i className="muted not-italic">Focus</i></span><span><b>{focus.topThreeShare}%</b><br/><i className="muted not-italic">Top 3</i></span><span><b>{focus.activeRepositories}</b><br/><i className="muted not-italic">Active</i></span></div></Panel></section>
  <section className="mt-2 grid gap-2 xl:grid-cols-[1.35fr_.65fr]"><Panel title="90-Day Activity Heatmap" sub="Score · hover for details"><div className="grid grid-flow-col grid-rows-7 gap-1 overflow-x-auto">{heat.map(d=><div key={d.date} className="h-3 w-3 rounded-[2px]" title={`${d.date} · ${d.commits} commits · ${fmt.format(d.changedLines)} lines · ${d.activeRepositories} repos`} style={{background:d.score?`color-mix(in srgb, #39d353 ${20+d.score/maxHeat*80}%, #161b22)`:"#161b22"}}/>)}</div><div className="muted mt-2 text-[9px]">Less ▪ ▪ ▪ ▪ More</div></Panel><Panel title="Repository Momentum" sub="参考値 · recent 7d / prior weekly avg"><div className="grid grid-cols-3 gap-2">{(["HOT","STABLE","COOLING"] as const).map(b=><div key={b}><p className={`mb-1 text-[9px] font-bold ${b==="HOT"?"text-[#f0883e]":b==="COOLING"?"text-[#79c0ff]":"text-[#7ee787]"}`}>{b}</p>{rows.filter(r=>momentum[r.repository.fullName].band===b).slice(0,3).map(r=><div key={r.repository.id} className="mb-1 flex justify-between gap-1 text-[9px]"><span className="truncate">{r.repository.name}</span><b>{momentum[r.repository.fullName].value}x</b></div>)}</div>)}</div></Panel></section>
  <section className="panel mt-2 overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line)] px-3 py-2"><h2 className="text-[11px] font-bold uppercase tracking-wider text-[#7ee787]">Repository Activity Matrix</h2><span className="muted text-[9px]">Click metric headers to sort · {rows.length} tracked</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-[10px]"><thead className="muted bg-black/20"><tr><th className="px-3 py-2">Repository</th>{[["Today","commits"],["7d","commits"],["30d","commits"],["Commits","commits"],["+",null],["-",null],["Files","changedFiles"],["Days","activeDays"],["Score","score"],["Momentum","momentum"],["Last Push","pushedAt"]].map(([l,k],i)=><th key={`${l}-${i}`} className="px-2 py-2"><button disabled={!k} onClick={()=>k&&setSort(k as SortKey)} className={k?"hover:text-white":""}>{l}{sort===k?" ↓":""}</button></th>)}</tr></thead><tbody>{rows.map(r=>{const m=r.metrics[period],mo=momentum[r.repository.fullName];return <tr key={r.repository.id} className="border-t border-[var(--line)] hover:bg-white/[.025]"><td className="px-3 py-2"><Link href={`/repositories/${encodeURIComponent(r.repository.owner)}/${encodeURIComponent(r.repository.name)}`} className="font-semibold hover:text-[#7ee787]">{r.repository.name}</Link><span className="muted ml-2">{r.repository.language??"—"}</span></td><td className="px-2">{r.metrics.today.commits}</td><td className="px-2">{r.metrics.week.commits}</td><td className="px-2">{r.metrics.month.commits}</td><td className="px-2">{m.commits}</td><td className="px-2 text-[#56d364]">+{m.additions}</td><td className="px-2 text-[#f85149]">-{m.deletions}</td><td className="px-2">{m.changedFiles}</td><td className="px-2">{m.activeDays}</td><td className="px-2 font-semibold">{m.score.toFixed(1)}</td><td className="px-2">{mo.value}x</td><td className="muted px-2">{dateFmt(r.repository.pushedAt)}</td></tr>})}</tbody></table></div></section>
  <section className="mt-2 grid gap-2 md:grid-cols-2 xl:grid-cols-4"><Panel title="Commit Size Distribution"><Bars items={data.analysis.commitSizes[period].map(b=>({label:`${b.key} · ${b.label}`,value:b.count,text:String(b.count)}))}/></Panel><Panel title="Day × Hour"><div className="grid grid-cols-5 gap-1 text-center text-[9px]"><span/>{slots.map(s=><span key={s} className="muted">{s}</span>)}{days.flatMap((d,di)=>[<span key={d} className="muted text-left">{d}</span>,...data.analysis.dayHour[period].filter(c=>c.day===di).map(c=><span key={`${di}-${c.slot}`} title={`${d} ${slots[c.slot]}: ${c.commits}`} className="rounded py-1" style={{background:c.commits?`rgb(35 134 54 / ${.2+c.commits/maxHour*.8})`:"#161b22"}}>{c.commits}</span>)])}</div></Panel><Panel title="Language Activity" sub="Primary language proxy"><Bars items={data.analysis.languages[period].map(l=>({label:l.language,value:l.score,text:`${l.share}%`}))}/></Panel><Panel title="Week over Week"><table className="w-full text-[9px]"><thead className="muted"><tr><th className="text-left">Metric</th><th>This</th><th>Last</th><th>Δ</th></tr></thead><tbody>{data.analysis.weekComparison.map(r=><tr key={r.key} className="border-t border-[var(--line)]"><td className="py-1.5">{r.label}</td><td className="text-center">{compact.format(r.current)}</td><td className="text-center">{compact.format(r.previous)}</td><td className={`text-right ${(r.change??0)>=0?"text-[#56d364]":"text-[#f85149]"}`}>{r.change===null?"NEW":`${r.change>=0?"+":""}${r.change}${r.absolute?"":"%"}`}</td></tr>)}</tbody></table><div className="mt-2 border-t border-[var(--line)] pt-2">{data.analysis.repositoryWeekChange.slice(0,4).map(r=><div key={r.repository} className="flex justify-between text-[9px]"><span className="truncate">{r.repository}</span><span>{r.change===null?"NEW":`${r.change>=0?"+":""}${r.change}%`}</span></div>)}</div></Panel></section>
  <footer className="muted mt-2 flex justify-between text-[9px]"><span>@{data.username} · Generated {dateFmt(data.generatedAt)} JST</span><span>API {data.rateLimit?`${fmt.format(data.rateLimit.remaining)} / ${fmt.format(data.rateLimit.limit)}`:"unavailable"}</span></footer></main>;
}
