"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { DailyChart } from "./daily-chart";
import type { DashboardData, Metrics, PeriodKey } from "@/types/activity";

const periods: { key: PeriodKey; label: string }[] = [{ key: "today", label: "Today" }, { key: "week", label: "7 Days" }, { key: "month", label: "30 Days" }];
const number = new Intl.NumberFormat("en-US");
const formatDate = (date: string | null) => date ? new Intl.DateTimeFormat("ja-JP", { timeZone: "Asia/Tokyo", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(date)) : "—";

export function Dashboard({ data }: { data: DashboardData }) {
  const [period, setPeriod] = useState<PeriodKey>("week");
  const ranked = useMemo(() => [...data.repositories].sort((a, b) => b.metrics[period].score - a.metrics[period].score), [data.repositories, period]);
  const summary = ranked.reduce<Metrics>((sum, item) => ({ commits: sum.commits + item.metrics[period].commits, activeDays: 0, additions: sum.additions + item.metrics[period].additions, deletions: sum.deletions + item.metrics[period].deletions, changedLines: sum.changedLines + item.metrics[period].changedLines, changedFiles: sum.changedFiles + item.metrics[period].changedFiles, score: 0 }), { commits: 0, activeDays: 0, additions: 0, deletions: 0, changedLines: 0, changedFiles: 0, score: 0 });
  const visibleDays = period === "today" ? 1 : period === "week" ? 7 : 30;
  const activeDays = data.dailyActivity.slice(-visibleDays).filter((day) => day.commits > 0).length;
  const maxScore = Math.max(1, ...ranked.map((item) => item.metrics[period].score));
  return <main className="shell">
    <header className="flex flex-wrap items-end justify-between gap-5 border-b border-[var(--line)] pb-6"><div><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-[var(--green)] shadow-[0_0_14px_#3fb950]" /><p className="eyebrow">Live from GitHub</p></div><h1 className="mt-3 text-3xl font-semibold tracking-tight">Development Overview</h1><p className="muted mt-2 text-sm">@{data.username} · 複数Repositoryの開発活動</p></div><div className="flex rounded-lg border border-[var(--line)] bg-[#0d1117] p-1">{periods.map((item) => <button key={item.key} onClick={() => setPeriod(item.key)} aria-pressed={period === item.key} className={`rounded-md px-4 py-2 text-xs font-semibold transition ${period === item.key ? "bg-[#238636] text-white" : "muted hover:text-white"}`}>{item.label}</button>)}</div></header>
    {data.warnings.length > 0 && <div className="mt-4 rounded-lg border border-amber-800/60 bg-amber-950/20 px-4 py-3 text-xs text-amber-200">一部データを取得できませんでした（{data.warnings.length}件）。取得済みの結果を表示しています。</div>}
    <section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Total commits", summary.commits], ["Changed lines", summary.changedLines], ["Active repositories", ranked.filter((r) => r.metrics[period].commits > 0).length], ["Active days", activeDays]].map(([label, value]) => <article key={label} className="panel p-5"><p className="muted text-[11px] uppercase tracking-wider">{label}</p><p className="mt-3 text-3xl font-semibold tabular-nums">{number.format(Number(value))}</p></article>)}</section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[1.05fr_.95fr]"><article className="panel p-5"><div className="flex items-start justify-between"><div><p className="eyebrow">Development activity</p><h2 className="mt-2 text-lg font-semibold">今いちばん触っているRepository</h2></div><span className="muted text-[10px]">Scoreは参考値</span></div><div className="mt-6 space-y-4">{ranked.slice(0, 6).map((item, index) => <div key={item.repository.id}><div className="mb-1.5 flex justify-between gap-4 text-xs"><span className="truncate"><b className="mr-3 text-[var(--green)]">{String(index+1).padStart(2,"0")}</b>{item.repository.name}</span><span className="muted tabular-nums">{item.metrics[period].score.toFixed(1)}</span></div><div className="h-2 overflow-hidden rounded-full bg-[#21262d]"><div className="h-full rounded-full bg-gradient-to-r from-[#238636] to-[#56d364]" style={{ width: `${(item.metrics[period].score/maxScore)*100}%` }} /></div></div>)}</div></article>
      <article className="panel grid-lines p-5"><p className="eyebrow">Daily activity</p><h2 className="mt-2 text-lg font-semibold">30-day commit pulse</h2><div className="mt-4"><DailyChart data={data.dailyActivity} /></div></article></section>
    <section className="panel mt-4 overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line)] p-5"><div><p className="eyebrow">Repositories</p><h2 className="mt-2 text-lg font-semibold">Activity breakdown</h2></div><span className="muted text-xs">{ranked.length} tracked</span></div>{ranked.length === 0 ? <div className="p-12 text-center"><h3>対象Repositoryがありません</h3><p className="muted mt-2 text-sm">除外設定またはGitHub Tokenの権限を確認してください。</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[840px] text-left text-xs"><thead className="muted bg-black/20 uppercase"><tr>{["Repository","Commits","Active days","Additions","Deletions","Score","Last push"].map((h) => <th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{ranked.map((item) => { const m=item.metrics[period]; return <tr key={item.repository.id} className="border-t border-[var(--line)] hover:bg-white/[.025]"><td className="px-5 py-4"><Link className="font-semibold hover:text-[var(--green)]" href={`/repositories/${encodeURIComponent(item.repository.owner)}/${encodeURIComponent(item.repository.name)}`}>{item.repository.name}</Link><div className="muted mt-1 flex gap-2"><span>{item.repository.private ? "PRIVATE" : "PUBLIC"}</span><span>{item.repository.language ?? "—"}</span></div></td><td className="px-5 py-4 tabular-nums">{m.commits}</td><td className="px-5 py-4 tabular-nums">{m.activeDays}</td><td className="px-5 py-4 tabular-nums text-[#56d364]">+{number.format(m.additions)}</td><td className="px-5 py-4 tabular-nums text-[#f85149]">-{number.format(m.deletions)}</td><td className="px-5 py-4 tabular-nums">{m.score.toFixed(1)}</td><td className="muted px-5 py-4">{formatDate(item.repository.pushedAt)}</td></tr>; })}</tbody></table></div>}</section>
    <footer className="muted mt-5 flex flex-wrap justify-between gap-3 text-[10px]"><span>Generated {formatDate(data.generatedAt)} JST</span><span>GitHub API · {data.rateLimit ? `Remaining ${number.format(data.rateLimit.remaining)} / ${number.format(data.rateLimit.limit)}` : "Rate limit unavailable"}</span></footer>
  </main>;
}
