import type { AnomalyAnalysis, ChangeEvent, ChangeSeverity, CommitActivity, DayComparison, FocusMetrics, Metrics, RepositoryActivity, ShareShift, TimeShare, WeekHighlights } from "@/types/activity";
import { calculateActivityScore } from "../activity-score";
import { getJstStart, toJstDateKey } from "../date-range";
import { ANOMALY_THRESHOLDS as T, SEVERITY_RANK } from "./config";

const DAY=86_400_000;
function metrics(commits:CommitActivity[]):Metrics{const additions=commits.reduce((s,c)=>s+c.additions,0),deletions=commits.reduce((s,c)=>s+c.deletions,0),changedFiles=commits.reduce((s,c)=>s+c.changedFiles,0),activeDays=new Set(commits.map(c=>toJstDateKey(c.authoredAt))).size;const base={commits:commits.length,activeDays,additions,deletions,changedLines:additions+deletions,changedFiles};return{...base,score:calculateActivityScore(base)}}
const inRange=(items:CommitActivity[],start:Date,end:Date)=>items.filter(c=>{const d=new Date(c.authoredAt);return d>=start&&d<end});
const pct=(current:number,previous:number)=>previous===0?(current===0?0:null):Math.round((current-previous)/previous*100);
function percentileValue(values:number[],p:number){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.ceil(p*sorted.length)-1]}
function focusFor(items:Metrics[]):FocusMetrics{const active=items.filter(m=>m.score>0).sort((a,b)=>b.score-a.score),total=active.reduce((s,m)=>s+m.score,0),top=total?(active[0]?.score??0)/total*100:0,top3=total?active.slice(0,3).reduce((s,m)=>s+m.score,0)/total*100:0;return{score:total?Math.round(Math.min(100,top*.65+top3*.35)):0,topShare:Math.round(top),topThreeShare:Math.round(top3),activeRepositories:active.length}}
function event(id:string,type:ChangeEvent["type"],category:ChangeEvent["category"],severity:ChangeSeverity,title:string,description:string,now:Date,repository?:string,value?:number,baseline?:number):ChangeEvent{return{id,type,category,severity,title,description,repository,value,baseline,detectedAt:now.toISOString()}}
function slots(commits:CommitActivity[]){const result=[0,0,0,0];for(const c of commits){const hour=Number(new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",hour:"numeric",hourCycle:"h23"}).format(new Date(c.authoredAt)));result[Math.floor(hour/6)]++}return result}

export function detectBurst(commits:CommitActivity[]):{count:number;minutes:number}|null{const sorted=commits.map(c=>new Date(c.authoredAt).getTime()).sort((a,b)=>a-b);for(const [minutes,count] of [[T.burstShortMinutes,T.burstShortCount],[T.burstLongMinutes,T.burstLongCount]] as const){for(let i=0;i<sorted.length;i++){let j=i;while(j<sorted.length&&sorted[j]-sorted[i]<=minutes*60_000)j++;if(j-i>=count)return{count:j-i,minutes}}}return null}

export function buildAnomalyAnalysis(repositories:RepositoryActivity[],now=new Date(),focusCurrent?:FocusMetrics):AnomalyAnalysis{
  const all=repositories.flatMap(r=>r.commits),end=new Date(now.getTime()+1),todayStart=getJstStart("today",now),weekStart=getJstStart("week",now),previousWeekStart=new Date(weekStart.getTime()-7*DAY),priorStart=new Date(weekStart.getTime()-21*DAY),monthStart=getJstStart("month",now);
  const today=inRange(all,todayStart,end),yesterday=inRange(all,new Date(todayStart.getTime()-DAY),todayStart),previousDaily=inRange(all,new Date(todayStart.getTime()-7*DAY),todayStart);const dailyBaseline=previousDaily.length/7,ratio=dailyBaseline?today.length/dailyBaseline:(today.length?4:1);const changePercent=dailyBaseline?pct(today.length,dailyBaseline):null;const level=ratio>=3?"VERY HIGH":ratio>=1.5?"HIGH":ratio<.5?"LOW":"NORMAL";
  const pulse={level,todayCommits:today.length,activeRepositories:new Set(today.map(c=>c.repository)).size,changePercent,baseline:Math.round(dailyBaseline*10)/10} as const;
  const dayOverDay:DayComparison[]=[["Commits",today.length,yesterday.length],["Changed Lines",metrics(today).changedLines,metrics(yesterday).changedLines],["Files Changed",metrics(today).changedFiles,metrics(yesterday).changedFiles],["Active Repos",new Set(today.map(c=>c.repository)).size,new Set(yesterday.map(c=>c.repository)).size]].map(([label,current,previous])=>({label:String(label),today:Number(current),yesterday:Number(previous),change:pct(Number(current),Number(previous))}));
  const events:ChangeEvent[]=[];const currentScores=new Map<string,number>(),previousScores=new Map<string,number>();
  const previousMonthStart=new Date(monthStart.getTime()-30*DAY),monthScore=metrics(inRange(all,monthStart,end)).score,previousMonthScore=metrics(inRange(all,previousMonthStart,monthStart)).score,monthChange=pct(monthScore,previousMonthScore);
  if(monthChange!==null&&Math.abs(monthChange)>=50&&(monthScore>=T.minimumRecentScore||previousMonthScore>=T.minimumBaselineScore))events.push(event("monthly-activity",monthChange>0?"activity-spike":"activity-drop","activity",Math.abs(monthChange)>=100?"strong":"notable",`Monthly activity ${monthChange>0?"increased":"decreased"}`,`${monthChange>0?"+":""}${monthChange}% vs the previous 30 days`,now,undefined,monthScore,previousMonthScore));
  for(const repo of repositories){const name=repo.repository.name,full=repo.repository.fullName,current=inRange(repo.commits,weekStart,end),previous=inRange(repo.commits,previousWeekStart,weekStart),prior=inRange(repo.commits,priorStart,weekStart),cm=metrics(current),pm=metrics(previous),baseline=metrics(prior).score/3;currentScores.set(full,cm.score);previousScores.set(full,pm.score);const momentum=baseline?cm.score/baseline:(cm.score?4:0);
    const priorMonth=metrics(inRange(repo.commits,monthStart,weekStart)),isInactive=cm.score<=T.inactiveRecentScore&&priorMonth.score>=T.inactivePriorScore;
    if(isInactive)events.push(event(`inactive-${full}`,"inactive","repository","notable",`${name} is recently inactive`,`Previously active this month; little activity in the last 7 days`,now,name,cm.score,priorMonth.score));
    else if((baseline>=T.minimumBaselineScore||cm.score>=T.minimumRecentScore)&&momentum>=T.rising){events.push(event(`activity-${full}`,"activity-spike","activity",momentum>=T.strongSpike?"strong":"notable",`${name} activity surged`,`${momentum.toFixed(1)}x its recent weekly baseline${pct(cm.score,baseline)!==null?` (${pct(cm.score,baseline)!}% change)`:""}`,now,name,momentum,baseline))}
    else if(baseline>=T.minimumBaselineScore&&momentum<T.cooling){events.push(event(`activity-${full}`,"activity-drop","activity",momentum<T.strongDrop?"strong":"notable",`${name} activity cooled`,`${Math.round((1-momentum)*100)}% below its recent weekly baseline`,now,name,momentum,baseline))}
    const history=inRange(repo.commits,new Date(now.getTime()-90*DAY),weekStart),sizes=history.map(c=>c.additions+c.deletions),threshold=sizes.length>=T.largeCommitMinimumSample?percentileValue(sizes,T.largeCommitPercentile):T.largeCommitFallbackLines;const large=[...current].sort((a,b)=>(b.additions+b.deletions)-(a.additions+a.deletions))[0];if(large&&large.additions+large.deletions>=threshold)events.push(event(`large-${full}`,"large-commit","commit","strong",`${name} had an unusually large commit`,`${(large.additions+large.deletions).toLocaleString("en-US")} changed lines · typical p95 ${Math.round(percentileValue(sizes,.95)).toLocaleString("en-US")}`,now,name,large.additions+large.deletions,threshold));
    const burst=detectBurst(current);if(burst)events.push(event(`burst-${full}`,"commit-burst","commit","notable",`${name} had a commit burst`,`${burst.count} commits within ${burst.minutes} minutes`,now,name,burst.count,burst.minutes));
    const sorted=[...repo.commits].sort((a,b)=>new Date(b.authoredAt).getTime()-new Date(a.authoredAt).getTime());const recent=sorted.find(c=>new Date(c.authoredAt)>=weekStart);const before=sorted.find(c=>new Date(c.authoredAt)<weekStart);if(recent&&!before)events.push(event(`new-${full}`,"new-activity","repository","info",`New project activity: ${name}`,"First activity detected in the 90-day observation window",now,name));else if(recent&&before){const gap=(new Date(recent.authoredAt).getTime()-new Date(before.authoredAt).getTime())/DAY;if(gap>=T.revivalGapDays)events.push(event(`revived-${full}`,"revived","repository","notable",`${name} activity resumed`,`Activity resumed after ${Math.floor(gap)} days`,now,name,gap,T.revivalGapDays))}
  }
  const currentTotal=[...currentScores.values()].reduce((a,b)=>a+b,0),previousTotal=[...previousScores.values()].reduce((a,b)=>a+b,0);const shareShifts:ShareShift[]=repositories.map(r=>{const c=currentTotal?(currentScores.get(r.repository.fullName)??0)/currentTotal*100:0,p=previousTotal?(previousScores.get(r.repository.fullName)??0)/previousTotal*100:0;return{repository:r.repository.name,current:Math.round(c),previous:Math.round(p),points:Math.round(c-p)}}).filter(s=>Math.abs(s.points)>=T.shareShiftPoints).sort((a,b)=>Math.abs(b.points)-Math.abs(a.points));for(const s of shareShifts.slice(0,2))events.push(event(`share-${s.repository}`,"share-shift","repository","notable",`${s.repository} share shifted ${s.points>0?"up":"down"}`,`${s.previous}% → ${s.current}% (${s.points>0?"+":""}${s.points}pt)`,now,s.repository,s.current,s.previous));
  const previousFocus=focusFor(repositories.map(r=>metrics(inRange(r.commits,previousWeekStart,weekStart)))),currentFocus=focusCurrent??focusFor(repositories.map(r=>metrics(inRange(r.commits,weekStart,end))));const focusPoints=currentFocus.score-previousFocus.score;if(Math.abs(focusPoints)>=T.focusShiftPoints)events.push(event("focus-shift","focus-shift","pattern","notable",`Development became more ${focusPoints>0?"concentrated":"distributed"}`,`Focus Score ${previousFocus.score} → ${currentFocus.score} (${focusPoints>0?"+":""}${focusPoints})`,now,undefined,currentFocus.score,previousFocus.score));
  const recentSlots=slots(inRange(all,weekStart,end)),baseSlots=slots(inRange(all,priorStart,weekStart)),recentSlotTotal=recentSlots.reduce((a,b)=>a+b,0),baseSlotTotal=baseSlots.reduce((a,b)=>a+b,0);const timeShares:TimeShare[]=recentSlots.map((count,slot)=>{const recent=recentSlotTotal?count/recentSlotTotal*100:0,baseline=baseSlotTotal?baseSlots[slot]/baseSlotTotal*100:0;return{slot,recent:Math.round(recent),baseline:Math.round(baseline),points:Math.round(recent-baseline)}});const timeShift=[...timeShares].sort((a,b)=>Math.abs(b.points)-Math.abs(a.points))[0];if(timeShift&&Math.abs(timeShift.points)>=T.timeShiftPoints)events.push(event("time-shift","time-shift","pattern","notable",`${["Late-night","Morning","Afternoon","Evening"][timeShift.slot]} activity ${timeShift.points>0?"increased":"decreased"}`,`${timeShift.baseline}% → ${timeShift.recent}% (${timeShift.points>0?"+":""}${timeShift.points}pt)`,now,undefined,timeShift.recent,timeShift.baseline));
  const days=new Set(all.map(c=>toJstDateKey(c.authoredAt)));let streak=0,cursor=new Date(now);while(days.has(toJstDateKey(cursor))){streak++;cursor=new Date(cursor.getTime()-DAY)}if(streak>=3&&(streak===3||streak===7||streak%10===0))events.push(event("streak","streak","pattern","info",`${streak}-day development streak reached`,"A continuous activity run is in progress",now,undefined,streak));else if(streak===0){let previousStreak=0;cursor=new Date(now.getTime()-DAY);while(days.has(toJstDateKey(cursor))){previousStreak++;cursor=new Date(cursor.getTime()-DAY)}if(previousStreak>=3)events.push(event("streak-ended","streak","pattern","info",`Previous streak ended at ${previousStreak} days`,"The activity pattern changed after a sustained run",now,undefined,previousStreak))}
  const weekdays=[0,0,0,0,0,0,0];for(const c of inRange(all,monthStart,end)){const label=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"short"}).format(new Date(c.authoredAt));const idx=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].indexOf(label);if(idx>=0)weekdays[idx]++}
  const changes=repositories.map(r=>{const c=currentScores.get(r.repository.fullName)??0,p=previousScores.get(r.repository.fullName)??0;return{repository:r.repository.name,current:c,previous:p,change:pct(c,p)}});const comparable=changes.filter(c=>c.change!==null&&c.current+c.previous>=T.minimumRecentScore);const pick=(row:typeof comparable[number]|undefined)=>row&&row.change!==null?{repository:row.repository,change:row.change}:undefined;const weekHighlights:WeekHighlights={increase:pick(comparable.filter(c=>c.change!>=0).sort((a,b)=>b.change!-a.change!)[0]),decrease:pick(comparable.filter(c=>c.change!<0).sort((a,b)=>a.change!-b.change!)[0]),stable:pick([...comparable].sort((a,b)=>Math.abs(a.change!)-Math.abs(b.change!))[0]),newlyActive:changes.filter(c=>c.previous===0&&c.current>=T.minimumRecentScore).map(c=>c.repository)};
  const deduped=new Map<string,ChangeEvent>();for(const e of events.sort((a,b)=>SEVERITY_RANK[b.severity]-SEVERITY_RANK[a.severity]||Math.abs(b.value??0)-Math.abs(a.value??0))){const key=e.repository&&["activity-spike","activity-drop","inactive"].includes(e.type)?`activity-${e.repository}`:e.id;if(!deduped.has(key))deduped.set(key,e)}
  return{pulse,events:[...deduped.values()].slice(0,T.maxFeedEvents),dayOverDay,shareShifts,timeShares,weekdayActivity:weekdays,weekHighlights};
}
